apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: pomodoro-vpa
  namespace: fe-pomodoro
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: pomodoro-frontend
  updatePolicy:
    updateMode: "Auto"
    minReplicas: 1